using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SVGKit
{
	public enum SvgkaNgleType {
		SVG_ANGLETYPE_UNKNOWN = 0,
		SVG_ANGLETYPE_UNSPECIFIED = 1,
		SVG_ANGLETYPE_DEG = 2,
		SVG_ANGLETYPE_RAD = 3,
		SVG_ANGLETYPE_GRAD = 4
	}

	public enum SVG_LENGTH_TYPE {
		SVG_LENGTHTYPE_UNKNOWN = 0,
		SVG_LENGTHTYPE_NUMBER = 1,
		SVG_LENGTHTYPE_PERCENTAGE = 2,
		SVG_LENGTHTYPE_EMS = 3,
		SVG_LENGTHTYPE_EXS = 4,
		SVG_LENGTHTYPE_PX = 5,
		SVG_LENGTHTYPE_CM = 6,
		SVG_LENGTHTYPE_MM = 7,
		SVG_LENGTHTYPE_IN = 8,
		SVG_LENGTHTYPE_PT = 9,
		SVG_LENGTHTYPE_PC = 10
	}

	public enum SvgktRansformType {
		SVG_TRANSFORM_UNKNOWN = 0,
		SVG_TRANSFORM_MATRIX = 1,
		SVG_TRANSFORM_TRANSLATE = 2,
		SVG_TRANSFORM_SCALE = 3,
		SVG_TRANSFORM_ROTATE = 4,
		SVG_TRANSFORM_SKEWX = 5,
		SVG_TRANSFORM_SKEWY = 6
	}

	public struct SVGCurve
	{
		CGPoint c1;
		CGPoint c2;
		CGPoint p;
	}
}

